"""add puja_verification_submissions table

Revision ID: 6d16ff3014d3
Revises: 72c827cc963c
Create Date: 2026-09-11 13:17:28.993216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d16ff3014d3'
down_revision: Union[str, None] = '72c827cc963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###