"""initial database schema

Revision ID: 708babde5a14
Revises: 
Create Date: 2026-09-10 14:40:22.070366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708babde5a14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_category'), 'emergency_contacts', ['category'], unique=False)
    op.create_table('pujas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('opening_time', sa.String(length=20), nullable=True),
    sa.Column('closing_time', sa.String(length=20), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('toilet', sa.Boolean(), nullable=False),
    sa.Column('food', sa.Boolean(), nullable=False),
    sa.Column('medical_assistance', sa.Boolean(), nullable=False),
    sa.Column('accessibility', sa.Boolean(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('crowd_status', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pujas_area'), 'pujas', ['area'], unique=False)
    op.create_index(op.f('ix_pujas_name'), 'pujas', ['name'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('crowd_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crowd_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_reports_puja_id'), 'crowd_reports', ['puja_id'], unique=False)
    op.create_index(op.f('ix_crowd_reports_user_id'), 'crowd_reports', ['user_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('is_real_photo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_puja_id'), 'images', ['puja_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('puja_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_puja_id'), 'reports', ['puja_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_puja_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_images_puja_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_crowd_reports_user_id'), table_name='crowd_reports')
    op.drop_index(op.f('ix_crowd_reports_puja_id'), table_name='crowd_reports')
    op.drop_table('crowd_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_pujas_name'), table_name='pujas')
    op.drop_index(op.f('ix_pujas_area'), table_name='pujas')
    op.drop_table('pujas')
    op.drop_index(op.f('ix_emergency_contacts_category'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###